### ISSUE TITLE
how to upload video with mp4 extension?

### ISSUE THREAD

**Issue by xfishernet** [larkin-nz/cloudflare-stream#2]
how to upload video with mp4 extension? it's impossible? or only random token file name without extension?

**Comment by danzlarkin** [comment]
Hey @xfishernet,

To upload a file a first create an instance of `CloudflareStream` with your Cloudflare credentials.

Once you've done that you can call `upload` method on the instance that you've created, passing the path to the file on your local system (passed as `path`).

Alternately if you've like to pass from a [Buffer](https://nodejs.org/api/buffer.html#buffer_class_buffer) you can also do this by passing `buffer` rather than `path`. 

Example code follows;

_Firstly, create an instance of `CloudflareStream` and configure it with your Cloudflare credentials:_
```js
// Import the request package to use for fetching a file from a URL
import { default as request } from 'request';

// Import the CloudflareStream package
import { CloudflareStream } from 'cloudflare-stream';

// Create an uploader instance using CloudflareStream
const uploader = new CloudflareStream({

  // Cloudflare Email Address
  email: 'sam@example.com',

 // Cloudflare API Key
  key: 'c23864bc3ada9bf9c937810f62bb69a4e90b0'
});
```

_If you wish to upload a file from your local filesystem you could use the following:_
```js
// Upload a video file to Cloudflare Stream from a local file
const uploadPath = uploader.upload({

  // Cloudflare Zone ID
  zone: 'ca4239cdd6a52cec1e916a6cd0e2f629',

  // The path to video file on the local filesystem
  path: './videos/demo-video.mp4'
});
```

_If you wish to upload a video file from a URL into a buffer and upload it you could use the following:_
```js
// Define the URL to fetch and upload
const fileURL = 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4';

// Fetch the file from the URL using request as a buffer
request.get(fileURL, { encoding: null }, (e, r, buffer) => {

  // Upload a video file to Cloudflare Stream from a buffer
  const uploadBuffer = uploader.upload({

    // Cloudflare Zone ID
    zone: 'ca4239cdd6a52cec1e916a6cd0e2f629',

    // The buffer of the file URL
    buffer: buffer
  });
});
```

I hope this helps!
